### ISSUE TITLE
Checklist for deploying the registration page to phet-server

### ISSUE THREAD

**Issue by mattpen** [phetsims/website-meteor#9]
- [x] Finish QA tests phetsims/QA#70
- [x] phetsims/website#644 - and change date to actual publication date
- [x] Install Meteor on phet-server
- [x] Install MongoDB on phet-server
- [x] Initialize MongoDB Schools collection with NCES data
- [x] Update the httpd conf files to route registration/school pages to meteor backend on phet-cache1/2
- [x] Update the stunnel conf on phet-server and phet-cache1/2 to allow meteor traffic to pass through
- [x] Update the RHEL firewall to allow http connections on the meteor port (1/26374) or on all ports
- [x] Implement RHEL service file to automate process management

**Comment by mattpen** [comment]
Profile pages were deployed on 1/25/2016
